const initialState = {
  job: {
    title: '',
    vacancies: null,
    department: null,
    owner: '',
    assesment: null,
    webform:null,
    webform_name:"",
    assesment_name: '',
    member_ids: [],
    member_names: [],
    type: '',
    nature: '',
    education: [],
    education_names: [],
    speciality: '',
    description: '',
    exp_min: null,
    exp_max: null,
    salary_min: '',
    salary_max: '',
    salary_type: '',
    currency: '',
    city: '',
    state: null,
    job_boards: ['Linedin-id'],
    pipeline: null,
    pipeline_name: '',
    state_name: '',
    active: 1,
    owner_name:'',
    department_name:'',
    city_name:'',
  },
};
export default initialState;
